name: splitit_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  http: ^1.0.0
  riverpod_annotation: ^2.1.1
  flutter_dotenv: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  riverpod_generator: ^2.2.3
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
